#!/usr/bin/env python3
"""Derive the Frasers-mall → Moove bus-asset mapping and write docs/frasers-assets.md.

    python3 tools/frasers_assets.py

The app derives the same mapping live from the same files (see mapFrasersAssets() in
index.html); this script exists so the mapping is also reviewable in a diff — a package
whose route list moves because the bus network changed should show up in a pull request,
not only on someone's screen.

Rule (identical in both places, and the only rule):
  * a service is AT THE DOOR of a mall when one of its stops sits within RADIUS_M of the
    mall point — the same 400 m the app's reach ranking uses;
  * a regional package is that region's malls' services ranked by how many of the region's
    malls they touch, then by weekday boardings at the qualifying stops, capped at PACK_MAX
    (the selection palette holds 16 distinct colours, and 12 lines still read on one map).

Feeder services are included: Moove sells the bus, not its trunk/feeder classification.
They are flagged in the tables because the atlas does not draw them until they are selected.
"""
import json, math, os

ROOT = os.path.join(os.path.dirname(__file__), '..')
RADIUS_M = 400
PACK_MAX = 12
REGIONS = ['North', 'North-East', 'East', 'Central']


def load(name):
    with open(os.path.join(ROOT, 'data', name)) as f:
        return json.load(f)


def dist_m(lat1, lng1, lat2, lng2):
    dx = (lng2 - lng1) * 111320 * math.cos(math.radians((lat1 + lat2) / 2))
    dy = (lat2 - lat1) * 110540
    return math.hypot(dx, dy)


def main():
    malls = load('poi_frasers.json')
    stops = load('stops.json')
    volume = load('stop_volume.json')
    services = load('network.json')['services']
    feeder = {s['n']: s['feeder'] for s in services}
    name_of = {s['n']: s['name'] for s in services}

    stop_services = {}
    for s in services:
        for code in s['stops']:
            stop_services.setdefault(code, set()).add(s['n'])

    # per mall: which stops are in range, and what each service picks up there
    per_mall = {}
    for m in malls:
        near = [c for c, v in stops.items()
                if dist_m(m['lat'], m['lng'], v[1], v[0]) <= RADIUS_M]
        routes = {}
        for c in near:
            wd = volume.get(c, {}).get('wd', 0)
            for n in stop_services.get(c, ()):
                routes[n] = routes.get(n, 0) + wd
        per_mall[m['name']] = {'region': m['region'], 'kind': m['kind'],
                               'stops': sorted(near), 'routes': routes}

    def pack(region):
        mall_names = [m['name'] for m in malls if m['region'] == region]
        agg = {}
        for nm in mall_names:
            for n, wd in per_mall[nm]['routes'].items():
                cell = agg.setdefault(n, [0, 0])
                cell[0] += 1
                cell[1] += wd
        order = sorted(agg.items(), key=lambda kv: (-kv[1][0], -kv[1][1], kv[0]))
        return mall_names, len(agg), order[:PACK_MAX]

    out = ['# Frasers spaces → Moove bus assets', '',
           'Generated by `tools/frasers_assets.py`. Do not hand-edit — re-run it after any',
           'change to `data/poi_frasers.json`, `data/stops.json`, `data/network.json` or',
           '`data/stop_volume.json`.', '',
           f'A service is counted at a space when one of its stops is within **{RADIUS_M} m** of the',
           'space point. Boardings are weekday taps at those stops (LTA DataMall passenger volume);',
           'they size the stop, not the advertising — one bus is one asset however many services',
           'call there. Feeder services are marked `†`: the atlas keeps them out of the always-drawn',
           'trunk layer, but they are real Moove inventory and are selectable.', '']

    out += ['## The spaces', '',
            "Every Frasers Property Singapore space: the eleven malls from their FRx directory "
            'plus their office and business-park properties. **Two questions, not one: is it '
            'theirs, and is it open?** Robertson Walk was on the portfolio pages long after it '
            'ceased operations on 31 May 2025 — being listed is not the same fact as trading. '
            'Anything added here needs both answered.', '',
            '| Space | Type | Region | What it is | Stops within 400 m | Services at the door | Watch |',
            '| --- | --- | --- | --- | ---: | ---: | --- |']
    for m in malls:
        d = per_mall[m['name']]
        out.append(f"| {m['name']} | {m['type']} | {m['region']} | {m['kind']} | "
                   f"{len(d['stops'])} | {len(d['routes'])} | {m.get('note', '—')} |")
    out += ['',
            '**Deliberately absent** — each is a reasonable thing to expect, so each is named:',
            '',
            '- **Robertson Walk** — ceased operations 31 May 2025 (FRx benefits stopped 30 Apr '
            '2025); the site goes to a Frasers / Sekisui House residential redevelopment by 2028. '
            'Still tagged in OpenStreetMap.',
            '- **Changi City Point** — divested by FCT in 2023. Still tagged in OpenStreetMap.',
            '- **nex** — Frasers Centrepoint Trust half-owns it, but it is not one of Frasers '
            'Property Singapore\'s malls.',
            '- **Cross Street Exchange** — divested by FLCT to PAG, completed 31 March 2022.', '']

    # the smallest set of services that reaches every space — the question a seller is
    # actually asked ("what's the minimum buy that covers all of Frasers?")
    reach = {}
    for nm, d in per_mall.items():
        for n in d['routes']:
            reach.setdefault(n, set()).add(nm)
    load_of = lambda n: sum(per_mall[nm]['routes'].get(n, 0) for nm in per_mall)
    uncovered, min_cover = set(per_mall), []
    while uncovered:
        best = max(reach, key=lambda n: (len(reach[n] & uncovered), load_of(n)))
        if not reach[best] & uncovered:
            break
        min_cover.append((best, sorted(reach[best] & uncovered)))
        uncovered -= reach[best]
    out += ['## The minimum buy — every space, fewest services', '',
            f'**{len(min_cover)} services reach all {len(per_mall)} Frasers spaces.** Picked greedily '
            '(take the service covering the most still-uncovered spaces, ties broken by boardings); '
            'an exhaustive search over every smaller combination finds none, so this is the floor, '
            'not just a good try.', '',
            '| # | Service | Adds | Spaces it brings in |', '| ---: | --- | ---: | --- |']
    for i, (n, adds) in enumerate(min_cover, 1):
        out.append(f"| {i} | **{n}**{'†' if feeder[n] else ''} | {len(adds)} | {', '.join(adds)} |")
    out += ['', 'Selection string: `' + ', '.join(n for n, _ in min_cover) + '`', '']

    out += ['## Regional packages', '',
            f'Each package is the region\'s top {PACK_MAX} services: most of the region\'s spaces '
            'covered first, then most boardings at those spaces\' stops.', '']
    for region in REGIONS:
        mall_names, n_cand, top = pack(region)
        out += [f'### {region} — {", ".join(mall_names)}', '',
                f'{n_cand} services pass at least one of these spaces; the package takes '
                f'{len(top)}.', '',
                '| Service | Spaces covered | Weekday boardings at those stops | Route |',
                '| --- | ---: | ---: | --- |']
        for n, (covered, wd) in top:
            mark = '†' if feeder[n] else ''
            out.append(f'| **{n}**{mark} | {covered} of {len(mall_names)} | {wd:,} | {name_of[n]} |')
        # what the package actually delivers per mall — a package can name four malls and still
        # be thin at one of them, and the seller has to know which one before the meeting
        chosen = {n for n, _ in top}
        out += ['', 'Reaching each space:', '']
        for nm in mall_names:
            hit = sorted(chosen & set(per_mall[nm]['routes']))
            out.append(f"- **{nm}** — {len(hit)} of the {len(top)}: " + ', '.join(hit))
        out += ['', 'Selection string: `' + ', '.join(n for n, _ in top) + '`', '']

    out += ['## Every service, space by space', '']
    for m in malls:
        d = per_mall[m['name']]
        listed = sorted(d['routes'], key=lambda n: (-d['routes'][n], n))
        out += [f"**{m['name']}** ({len(listed)}) — "
                + ', '.join(n + ('†' if feeder[n] else '') for n in listed), '']

    path = os.path.join(ROOT, 'docs', 'frasers-assets.md')
    with open(path, 'w') as f:
        f.write('\n'.join(out))
    print(f'{len(malls)} spaces · '
          f'{len(set().union(*(set(d["routes"]) for d in per_mall.values())))} distinct services '
          f'within {RADIUS_M} m → docs/frasers-assets.md')
    for region in REGIONS:
        mall_names, n_cand, top = pack(region)
        print(f'  {region:11} {len(top):2} of {n_cand:3} candidates: '
              + ', '.join(n for n, _ in top))


if __name__ == '__main__':
    main()
